In [1]:
class Employee:
    numberOfEmployees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.numberOfEmployees+=1


def averagesalary(employee):
    total = sum(e.salary for e in employee)
    average = total / len(employee)
    return average

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        Employee.__init__(self,name, family, salary, department)

print("Employee 1: ")
employee1 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Employee 2: ")
employee2 = Employee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("Full Time Employee 1: ")
employee3 = FulltimeEmployee(input("Enter name: "),input("Family Members: "),int(input("Employee Salary: ")),input("Employee Department: "))
print("")
print("Number of employees: ",Employee.numberOfEmployees)
listofEmployees = [employee1, employee2]
avgsalary = averagesalary(listofEmployees)
print("Avg salary is :", avgsalary)

Employee 1: 
Enter name: nikhita
Family Members: 2
Employee Salary: 50000
Employee Department: security
Employee 2: 
Enter name: moni
Family Members: 2
Employee Salary: 30000
Employee Department: backend
Full Time Employee 1: 
Enter name: soumica
Family Members: 2
Employee Salary: 30000
Employee Department: front end

Number of employees:  3
Avg salary is : 40000.0


In [2]:
import numpy

random_vector = numpy.random.uniform(1, 20, 20)
print(random_vector)
print("")
print("")
reshaped_array = random_vector.reshape(4, 5)
print("")
print("")
print(reshaped_array)
reshaped_array[numpy.arange(4), numpy.argmax(reshaped_array, axis=1)] = 0
print("")
print("")
print(reshaped_array)

[ 2.4326064   4.69884211  6.00319635 14.90837197 16.39319299  3.85516063
 11.32766547 17.89610889  7.59118462 15.50262894  6.00553622 10.0656344
  8.62250124  5.13231986 13.55171489 11.86057268  7.0334025   1.47706652
 10.32037539  1.51868577]




[[ 2.4326064   4.69884211  6.00319635 14.90837197 16.39319299]
 [ 3.85516063 11.32766547 17.89610889  7.59118462 15.50262894]
 [ 6.00553622 10.0656344   8.62250124  5.13231986 13.55171489]
 [11.86057268  7.0334025   1.47706652 10.32037539  1.51868577]]


[[ 2.4326064   4.69884211  6.00319635 14.90837197  0.        ]
 [ 3.85516063 11.32766547  0.          7.59118462 15.50262894]
 [ 6.00553622 10.0656344   8.62250124  5.13231986  0.        ]
 [ 0.          7.0334025   1.47706652 10.32037539  1.51868577]]
